-- 코드를 입력하세요
SELECT H,MAX(C)
FROM
(SELECT 0 AS H,0 AS C
FROM ANIMAL_OUTS
UNION
SELECT 1 AS H,0 AS C
FROM ANIMAL_OUTS
UNION
SELECT 2 AS H,0 AS C
FROM ANIMAL_OUTS
UNION
SELECT 3 AS H,0 AS C
FROM ANIMAL_OUTS
UNION
SELECT 4 AS H,0 AS C
FROM ANIMAL_OUTS
UNION
SELECT 5 AS H,0 AS C
FROM ANIMAL_OUTS
UNION
SELECT 6 AS H,0 AS C
FROM ANIMAL_OUTS
UNION
SELECT 7 AS H,0 AS C
FROM ANIMAL_OUTS
UNION
SELECT 8 AS H,0 AS C
FROM ANIMAL_OUTS
UNION
SELECT 9 AS H,0 AS C
FROM ANIMAL_OUTS
UNION
SELECT 10 AS H,0 AS C
FROM ANIMAL_OUTS
UNION
SELECT 11 AS H,0 AS C
FROM ANIMAL_OUTS
UNION
SELECT 12 AS H,0 AS C
FROM ANIMAL_OUTS
UNION
SELECT 13 AS H,0 AS C
FROM ANIMAL_OUTS
UNION
SELECT 14 AS H,0 AS C
FROM ANIMAL_OUTS
UNION
SELECT 15 AS H,0 AS C
FROM ANIMAL_OUTS
UNION
SELECT 16 AS H,0 AS C
FROM ANIMAL_OUTS
UNION
SELECT 17 AS H,0 AS C
FROM ANIMAL_OUTS
UNION
SELECT 18 AS H,0 AS C
FROM ANIMAL_OUTS
UNION
SELECT 19 AS H,0 AS C
FROM ANIMAL_OUTS
UNION
SELECT 20 AS H,0 AS C
FROM ANIMAL_OUTS
UNION
SELECT 21 AS H,0 AS C
FROM ANIMAL_OUTS
UNION
SELECT 22 AS H,0 AS C
FROM ANIMAL_OUTS
UNION
SELECT 23 AS H,0 AS C
FROM ANIMAL_OUTS

UNION

(SELECT HOUR(DATETIME) AS H, COUNT(HOUR(DATETIME)) AS C
FROM ANIMAL_OUTS
GROUP BY H ))T
GROUP BY H
ORDER BY H