SELECT CASE
        WHEN SUM(CASE WHEN a.CATEGORY = 'Front End' THEN 1 ELSE 0 END) > 0 AND 
            SUM(CASE WHEN a.NAME = 'Python' THEN 1 ELSE 0 END) > 0 THEN 'A'
        WHEN SUM(CASE WHEN a.NAME = 'C#' THEN 1 ELSE 0 END) > 0 THEN 'B'
        WHEN SUM(CASE WHEN a.CATEGORY = 'Front End' THEN 1 ELSE 0 END) > 0 THEN 'C' 

END AS GRADE, b.ID, b.EMAIL

-- a.code 가 들어있으면 1 아님 0 -> True False 로 이용한다.
FROM SKILLCODES AS a LEFT OUTER JOIN DEVELOPERS AS b ON a.CODE & b.SKILL_CODE
GROUP BY b.ID, b.EMAIL
HAVING GRADE IS NOT null
ORDER BY GRADE, b.ID


